### ISSUE TITLE
TSC montly All-SIG meeting and roadmap board review (2/28/2023)

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/tsc#70]
In this meeting (last of the month) all SIGs are invited to present their backlog/project board/road map and communicate to other sigs what is happening and being worked on.

All SIGs - please attach your items here (link to board, backlog, etc) in comments.

See previous months meeting
https://github.com/o3de/tsc/blob/main/meetings/notes/joint-meeting-20230131.md

and example
https://github.com/o3de/tsc/issues/64

**Comment by lmbr-pip** [comment]
SIG/Network: https://github.com/orgs/o3de/projects/22/views/1 
* Mostly working on new O3DE multiplayer sample, which is driving a lot of underlying changes in O3DE (Audio & Vfx fixes, fixed profile builds with PAKs). 
* (Not O3DE but of note) AWS made an open source O3DE multiplayer scaler project (supports for launching 500 clients against an O3DE multiplayer server. New sample team is using this to drive networking performance changes for new multiplayer sample
* Will be adding some planned feature work around improving the experience of making redistributable builds

SIG/Security - No planned features, SIG is mostly administrative to ensure security issues are addressed in a timely manner.

**Comment by lmbr-pip** [comment]
(on behalf of ) SIG/Core 
* Starting the long road to deprecate `AZ_TracePrintf`: https://github.com/o3de/o3de/issues/14838

**Comment by chanmosq** [comment]
SIG Docs & Community: https://github.com/orgs/o3de/projects/15
- [Created a GitHub Action workflow that creates a PR to sync main-to-dev](https://github.com/o3de/o3de.org/pull/2245) - To keep `development` synced with `main` at a more regular cadence. Addresses issue where engineers were submitting docs to `development` and they did not have the latest documentation from `main`.
- Completed backlog refinement. Closed out [45 issues](https://github.com/o3de/o3de.org/issues?q=is%3Aissue+is%3Aclosed+closed%3A2023-01-31..2023-02-21+sort%3Aupdated-desc+) in o3de.org repo
- SIG D&C planning for new elections
- SIG D&C meeting moved to 1st Tuesday of the month. Triage remains weekly on Tuesdays.
- Working with sig-release to make Roadmaps discoverable from the documentation, Contributing Guide. (Making the roadmap discoverable in the main website is part of the website development plan, which is owned by Marketing.)

**Comment by tonybalandiuk** [comment]
@tonybalandiuk is unable to make it to this meeting, and the co-chair @vincent6767  may also miss it.

What we did last month
1. There are 3 SIGs left to create the roadmap according to the RFC.
2. Started discussion about what the repositories included in the process. This started due to an O3DE-extras discussion.
3. Started a discussion to increase community awareness of the roadmap by sharing those in the docs and main websites: https://github.com/o3de/sig-docs-community/issues/102. Collaborating with SIG-docs-community
4. Decided on the next release 23.05 on May 3rd, 2023: https://github.com/o3de/sig-release/issues/133 . Stabilization branch phase will start on March 15th, 2023 10 AM PST. If you have any concerns with the schedule please comment under the issue ASAP.
 
What we're going to do next month based on the SIG-Release roadmap: https://github.com/orgs/o3de/projects/29
1. Mar 15: Start the 23.05 stabilization process: https://github.com/o3de/sig-release/issues/133
2. Work with with docs-community, TSC, and marketing to surface the O3DE roadmaps on the O3DE websites: https://github.com/o3de/sig-release/issues/137
3. Decide criteria for repositories to be included in a release. https://github.com/o3de/sig-release/discussions/129
4. Decide whether to include o3des-extras as part of the O3DE release or not. 
5. Complete documentation of the O3DE release process: https://github.com/o3de/sig-release/issues/134

**Comment by vincent6767** [comment]
SIG-Release Updates
1. All SIGs now have a roadmap, except for SIG Security and Operations as they don't have any planned roadmap yet. Thanks, everyone for helping with this effort! https://github.com/orgs/o3de/projects?query=is%3Aopen+SIG . 

CC: @tonybalandiuk

**Comment by hultonha** [comment]
sig-simulation - https://github.com/orgs/o3de/projects/23

It's a tiny bit out of date but a new roadmap task to track articulation and robotic arm support will be created soon (see this RFC for details https://github.com/o3de/sig-simulation/issues/60

Tagging @lgleim and @epsilon-delta for visibility

**Comment by lumberyard-employee-dm** [comment]
SIG-Core https://github.com/orgs/o3de/projects/31/views/1

* SIG-Core is currently attempting to gather nominations for a Chair/Co-Chair: https://github.com/o3de/sig-core/issues/51
* Research into improving developer iteration speed of using O3DE (Split AzCore, AzFramework and AzToolsFramework into smaller libraries, based on usable roles, Convert AzCore, AzFramework and AzToolsFramework into shared libraries(.dlls, .so, .dylib) in non-monolithic TARGETS, Reduce the number of core gems that reside in the O3DE repo, Form solutions to reduce build times in high impact areas such SerializeContext, BehaviorContext, TypeInfo, EBus, Component ...)

**Comment by amzn-changml** [comment]
sig-build items:

- https://github.com/o3de/sig-build/pull/79 RFC on methods to reduce cost for AR
- https://github.com/o3de/o3de/issues/14733 on updates to min spec for Windows

**Comment by AMZN-alexpete** [comment]
I wanted to raise awareness that SIG-Content plans to
1. enable the canonical o3de remote repository in an empty state (no content) for the upcoming release, baring any unforeseen legal, security or technical issues that arise.
2.  once the official approval process has been completed, approved content will available via the canonical o3de remote repository and in the Project Manager (o3de.exe)

**Comment by Kadino** [comment]
SIG-Testing roadmap https://github.com/orgs/o3de/projects/35 currently has three prominent items:
* https://github.com/o3de/sig-testing/issues/63
* https://github.com/o3de/sig-testing/issues/62
  * https://github.com/o3de/sig-testing/issues/64 (dependent on metrics)

Feedback would be appreciated on the open RFC for https://github.com/o3de/sig-testing/pull/66
