### ISSUE TITLE
All-Sigs update and roadmap for June 27, 2023

### ISSUE THREAD

**Issue by nick-l-o3de** [o3de/tsc#84]
8AM Pacfic Time (US) in the TSC/TAC discord channel, will be the monthly "all sigs" status update and roadmap on 6/27/2023 (TUESDAY)

See the previous agenda for an example:
https://github.com/o3de/tsc/issues/80

Please attach links to the SIG roadmap (And anything to notify teams of in case of your absence, it will be read for you), in comments below. along with any agenda items.

**Comment by vincent6767** [comment]
SIG Release updates can be read here
https://github.com/o3de/sig-release/issues/200

**Comment by lumberyard-employee-dm** [comment]
Here is the Roadmap for SIG-Core: https://github.com/orgs/o3de/projects/31/views/1

Updates since May 2023 Meeting:
* The new [Archive System](https://github.com/o3de/sig-core/issues/56) work has been submitted to Development
Support for writing the new archive format has been added as PR: https://github.com/o3de/o3de/pull/16052
Support for reading the new archive format has been added as PR: https://github.com/o3de/o3de/pull/16129
* Settings Registry [JSON Import Support](https://github.com/o3de/o3de/pull/16175): The Settings Registry now supports importing additional JSON files through [$import](https://deploy-preview-2435--o3deorg.netlify.app/docs/user-guide/settings/import-settings-registry/) directive
